### ISSUE TITLE
To remove Mizar's dependency on kube-proxy.  [feature Request]

### ISSUE THREAD

**Issue by zzxgzgz** [CentaurusInfra/mizar#174]
**What would you like to be added**:
I'd like to have Mizar's dependency on kube-proxy to be replaced.  

**Why is this needed**:
This dependency is blocking Mizar's integration wtih KubeEdge.

**Comment by zasherif** [comment]
Related: https://github.com/futurewei-cloud/mizar/issues/123

**Comment by phudtran** [comment]
Fixed in #183
