### ISSUE TITLE
Setting MTU on master node to 9000 causes TLS Handshake timeouts.

### ISSUE THREAD

**Issue by phudtran** [CentaurusInfra/mizar#182]
Solution: Enable MTU discovery on the nodes with the command below.
`sysctl -w net.ipv4.tcp_mtu_probing=2`
Issue to be closed pending PRs

**Comment by zasherif** [comment]
This uncovers one more issue we need to fix in the Kind setup; we need also the MTU on docker-0 to be 9000 to simulate a real-network.

**Comment by phudtran** [comment]
Fixed.
