### ISSUE TITLE
[BUG] Provide eth0 workaround

### ISSUE THREAD

**Issue by clu2xlu** [CentaurusInfra/mizar#251]

**Comment by clu2xlu** [comment]
[HIGH PRIORITY]
Bug Description: if the default network interface is not named "eth0", the droplet will fail to create. The reason for that is, the physical interface is hard coded in [droplet](https://github.com/centaurus-cloud/mizar/blob/7ed5f3e017287b0e1c1b3fa554f49e741ce506c5/mizar/obj/droplet.py#L40)

To Do: Currently, mizar hardcoded all [physical interface](https://github.com/centaurus-cloud/mizar/blob/46d9659cf5522e0d9a288b2cb89b41129b6e3efe/mizar/common/rpc.py#L30-L50) as 'eth0' 
We need change the hardcoded file so that it can take variables, and the network interface name is determined by user. 
1) Change 'eth0' into a variable
2) During setup, we need allow user to configure the name of the default network interface. Then mizar will take it as the physical interface [phy_itf](https://github.com/centaurus-cloud/mizar/blob/46d9659cf5522e0d9a288b2cb89b41129b6e3efe/mizar/common/rpc.py#L30-L50)

**Comment by XiaoningDing** [comment]
fixed in #381
