### ISSUE TITLE
issue about the Mizar environment's deployment

### ISSUE THREAD

**Issue by PikaPikaW** [CentaurusInfra/mizar#483]
Hi, i'm from ustc team. We want to deploy a Mizar environment locally and meet some problem when creating endpoint. we use a vm and follow the steps [here](https://mizar.readthedocs.io/en/latest/user/getting_started/) to deploy Mizar.
The XML configuration file for the VM is as follows:
[miza-node-4.txt](https://github.com/CentaurusInfra/mizar/files/6476900/miza-node-4.txt)

and Linux kernel version meets the requirements
```shell
sdn@miza:~$ uname -r
5.10.26-051026-generic
```
but creating the endpoints still fails. i use the example yaml file:
<details>
  <summary>create_endpoint.yaml</summary>
  <pre><code> 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
  </code></pre>
</details>

The relevant information is as follows:
<details>
  <summary>kubectl get pods</summary>
  <pre><code>
sdn@miza:~$ sudo kubectl get pods
NAME                                READY   STATUS
mizar-daemon-5q9h4                  1/1     Running
mizar-daemon-5vkj2                  1/1     Running
mizar-daemon-grmgv                  1/1     Running
mizar-daemon-h5jz7                  1/1     Running
mizar-operator-78b97798fb-brbt6     1/1     Running
nginx-deployment-5bf87f5f59-5pgpj   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-bfw97   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-bgwtv   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-bqcl7   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-bt7gs   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-cqrxq   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-hxc4d   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-lgk75   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-t9v4t   0/1     ContainerCreating
nginx-deployment-5bf87f5f59-wgdrt   0/1     ContainerCreating
  </code></pre>
</details>

sudo kubectl describe pods nginx-deployment-5bf87f5f59-wgdrt:
<details>
  <summary>kubectl describe pods</summary>
  <pre><code>
......
Events:
  Type     Reason          From                   Message
  ----     ------          ----                   -------
  Normal   Scheduled       default-scheduler      Successfully assigned default/nginx-deployment-5bf87f5f59-wgdrt to kind-worker2
  Normal   Logging         kopf                   Handler 'builtins_on_pod' succeeded.
  Normal   Logging         kopf                   Creation event is processed: 1 succeeded; 0 failed.
  Warning  FailedCreatePodSandBox     kubelet, kind-worker2  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fe5e39f658e138764c537420b329072d7b64b79a956529d59020f57d01ebb588": netplugin failed with no error message
  Warning  FailedCreatePodSandBox     kubelet, kind-worker2  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2674956909eeb730a0c88b521bd26e361ac9941ce75c1597e2cb4f1e502c02c5": netplugin failed with no error message
attach kind-worker2 container to view the logs (journalctl -u kubelet | tail):
May 09 08:59:14 kind-worker2 kubelet[435]: E0509 08:59:14.179136  435 kuberuntime_manager.go:727] createPodSandbox for pod "nginx-deployment-5bf87f5f59-wgdrt_default(86cd826f-d049-4082-b28a-4564fad072e2)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "0c9dc5bbfe066fd8c4dec1ae1cf91d47fb69bf0dcda7e2fed51f9926c26bad8c": netplugin failed with no error message
May 09 08:59:14 kind-worker2 kubelet[435]: E0509 08:59:14.179168  435 pod_workers.go:191] Error syncing pod 86cd826f-d049-4082-b28a-4564fad072e2 ("nginx-deployment-5bf87f5f59-wgdrt_default(86cd826f-d049-4082-b28a-4564fad072e2)"), skipping: failed to "CreatePodSandbox" for "nginx-deployment-5bf87f5f59-wgdrt_default(86cd826f-d049-4082-b28a-4564fad072e2)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-deployment-5bf87f5f59-wgdrt_default(86cd826f-d049-4082-b28a-4564fad072e2)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"0c9dc5bbfe066fd8c4dec1ae1cf91d47fb69bf0dcda7e2fed51f9926c26bad8c\": netplugin failed with no error message"
  </code></pre>
</details>

**Comment by vinaykul** [comment]
Can you please sync to commit https://github.com/CentaurusInfra/mizar/commit/bc02fb3004c14fd484c79549c62cb0263188c9ec and retry? Thanks,

**Comment by vinaykul** [comment]
We have Mizar working reliably now after fixing several issues. I will close this issue. Please reopen or create new issue if you still see problems.
