### ISSUE TITLE
XDP program fails to load when benchmark=True is set in Mizar kind-setup deployment

### ISSUE THREAD

**Issue by vinaykul** [CentaurusInfra/mizar#485]
To repro this issue, do the following:
1. In mizar codebase, set benchmark=true in mizar/common/rpc.py and mizar/daemon/interface_service.py
2. Deploy a two-worker kind cluster: './kind-setup dev 2'
3. Inspect the XDP programs loaded on veth-hostep@eth-hostep in the kind-worker nodes. This would be missing.
4. Inspect the mizar-daemon logs. It contains message such as "bpf failed to load program permission denied"
5. The above does not occur when running with DEBUG enabled (i.e. ebp_debug.o programs are loaded)

This should work regardless of whether _ebpf.o or ebpf_debug.o program binaries are used.

**Comment by vinaykul** [comment]
I think we can consider this issue fixed. Wei: If there's nothing else left to do for this issue, could you please close it? thx

**Comment by w-yue** [comment]
This issue is fixed in https://github.com/CentaurusInfra/mizar/pull/537. Close it now.
