### ISSUE TITLE
[Question] Will mizar be rewritten with go?

### ISSUE THREAD

**Issue by ghost** [CentaurusInfra/mizar#489]
Most CNIs are written with go, will mizar be  rewritten with go later?

**Comment by vinaykul** [comment]
We are planning to do this, but it is not scoped for the next release.

**Comment by withlin** [comment]
expect +1

**Comment by vinaykul** [comment]
We have the Mizar CNI driver in golang coming for the next release - tentative ETA is end of Sept.

**Comment by withlin** [comment]
good job!

**Comment by vinaykul** [comment]
Implemented in Mizar release v0.9
https://github.com/CentaurusInfra/mizar/releases/tag/v0.9
