### ISSUE TITLE
create a deployment in vanilla with the pods being allocated to a given VPC/subnet

### ISSUE THREAD

**Issue by chenqianfzh** [CentaurusInfra/mizar#505]
This feature is needed for integration with Kubernetes with Mizar as the networking control plane.

**Comment by vinaykul** [comment]
@chenqianfzh Please put together a 1-pager that clarifies the requirement and details a one or two user scenarios.

**Comment by chenqianfzh** [comment]
@vinaykul 

Per offline discussion, @pdgetrf  will assemble a 1-pager.

**Comment by pdgetrf** [comment]
Putting the 1-pager of requirement here.

For edge end-to-end test, we are requesting the following features from Mizar. Some may already exist, and are listed for verification. 

1. Run Mizar control and date plane in a K8s cluster
2. Provision VPCs and subnets with specified CIDR range. VPCs' CIDRs could overlap, but subnets within a VPC cannot have overlapped CIDR. 
3. VPCs and subnets are programmed into the Mizar data plane on nodes (ebpf maps through Mizar node agent)
4. For an edge cluster, subnets of a VPC could be distributed into different clusters, so Mizar should not force a cluster to have all the subnets of a VPC (if it does, what's the reason?)
5. Create pod and deployment into a specified VPC/subnet. This means the pod IPs are to be allocated from the specified subnet CIDR.
6. Divider redirects packet to an "endpoint" if provided (during startup or run time) when the target pod is in the same VPC but not in a subnet in the current cluster. This "endpoint" is a gateway process running in the cluster for edge communication.

With the above features, in an edge cluster, workloads could be created into a certain VPC. When a pod communicates with another pod in the same cluster, Mizar would work as usual. However, when the target pod is in a different cluster (also this means same VPC, different subnet), divider will forward the packet to a gateway endpoint if provided (at startup or during run time). For all other cases, divider will drop the packet.

**Comment by vinaykul** [comment]
@pdgetrf Can this issue be closed now?

**Comment by pdgetrf** [comment]
> @pdgetrf Can this issue be closed now?

yes please. thanks!
