### ISSUE TITLE
Fix bootstrap script to update kernel headers to the latest kernel if ver>=5.6.0

### ISSUE THREAD

**Issue by vinaykul** [CentaurusInfra/mizar#507]
Currently, if the kernel is older than 5.6.0 bootstrap script will invoke kernel-update that updates kernel as well as the header.
However, for already updated kernels, the update is skipped, and headers are not updated causing a build break. Todo: Update kernel headers if required to match kernel version if ver>=5.6.0

**Comment by click2cloud-team4** [comment]
Please assign this to **click2cloud-team2** , Thanks
