### ISSUE TITLE
Add Mizar support for predictable interface naming

### ISSUE THREAD

**Issue by vinaykul** [CentaurusInfra/mizar#519]
Currently, Mizar assumes that the interface name of primary interface in a single NIC system is "eth0". This is not true in the newer OSes that use naming such as "ens33" etc..

We need to fix the Mizar control plane code to handle this scenario.

**Comment by vinaykul** [comment]
We need this for the 9/30 milestone so Wei will work on fixing this issue.

**Comment by click2cloud-ashwin** [comment]
Hi @w-yue 

Recently I was working on this issue. I came to know that @vinaykul Sir assigned this issue to you. I have made some findings which may help you to resolve this issue.

I will share my internal public repo link. I hope, you will find it useful.

Kindly revert if any confusion arises.

**Comment by w-yue** [comment]
This issue is closed with solution https://github.com/CentaurusInfra/mizar/pull/555.
