### ISSUE TITLE
coredns pods issue

### ISSUE THREAD

**Issue by Hong-Chang** [CentaurusInfra/mizar#549]
There is coredns pods issue observed.

We have an earlier coredns pods issue and it hasn't been addressed so far. (Instable and restarting pods coredns-* and local-path-provisioner-* after deployment #545 https://github.com/CentaurusInfra/mizar/issues/545 ). But after a certain change, the issue seems different so here I file a new issue for tracking.

I'm using "git checkout #commitID" to go to different commit history to see what is the first commit cause the issue. Then the commit c7d6ab7fa221872acb18e5a3336c4a1417d131a8 is the one. When checking out to the code before the commit, the coredns issue behavior is #545. After the commit, the issue behavior is as this issue described.

The issue behavior:
In kind environment, use "./kind-setup.sh dev" to deploy mizar. Sometimes for the two coredns pods, the ready state will be 1/1 which is good. But sometimes they are 0/1. 
Even when they are running as 1/1, if delete the pod, and the pod will be recreated, now the new pod will be running as 0/1. This behavior is quite different than issue 545.

**Comment by vinaykul** [comment]
This has been fixed now.
