### ISSUE TITLE
Mizar cni log should be under /var/log

### ISSUE THREAD

**Issue by yb01** [CentaurusInfra/mizar#607]
**What happened**:

Currently Mizar cni puts its log under /tmp/mizarcni.log, all production logs should NOT be under /tmp. instead please put it under /var/log/

this is needed for Arktos VM runtime to setup the log , with Apparmor enabled, for all files that the runtime accesses, they will need to be set in the apparmor config.

Please make the change and Arktos-vm-runtime will make the changes per the new log path.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Mizar version:
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vinaykul** [comment]
Change path to /var/log. 
If possible, pick up log file from mizar cni config.
